/**
 * v3.5.0 — Opt-in pre-commit secrets hook script.
 *
 * A minimal, self-identifying bash script that shells out to `npx @gitwand/cli scan` in
 * `--strict --json` mode: the CLI's exit code decides whether the hook blocks the commit.
 * The marker comment (`SECRETS_HOOK_MARKER`) lets HooksPanel.vue detect a previously-installed
 * GitWand-managed pre-commit hook (vs. an unrelated user hook) without needing to store any
 * separate install-state — the hook script on disk IS the source of truth.
 */

export const SECRETS_HOOK_MARKER = "# gitwand-secrets-hook v1";

/** Builds the pre-commit hook script installed via `gitHookCreate(cwd, "pre-commit", ...)`. */
export function buildSecretsHookScript(): string {
  return [
    "#!/usr/bin/env bash",
    `${SECRETS_HOOK_MARKER} — do not edit; managed by GitWand`,
    "npx --no-install @gitwand/cli scan --staged --strict --json || {",
    '  echo "GitWand: potential secrets in staged changes (see above). Commit blocked."',
    '  echo "Bypass once with: git commit --no-verify"',
    "  exit 1",
    "}",
    "",
  ].join("\n");
}

/** `true` if `content` is (or was) generated by `buildSecretsHookScript()`. */
export function isSecretsHookScript(content: string): boolean {
  return content.includes(SECRETS_HOOK_MARKER);
}
