import { describe, it, expect } from "vitest";
import { SECRETS_HOOK_MARKER, buildSecretsHookScript, isSecretsHookScript } from "../secretsHook";

describe("buildSecretsHookScript", () => {
  it("contains the marker comment", () => {
    expect(buildSecretsHookScript()).toContain(SECRETS_HOOK_MARKER);
  });

  it("starts with a bash shebang on the first line", () => {
    const lines = buildSecretsHookScript().split("\n");
    expect(lines[0]).toBe("#!/usr/bin/env bash");
  });

  it("invokes gitwand scan --staged in strict/json hook mode", () => {
    const script = buildSecretsHookScript();
    expect(script).toContain("@gitwand/cli scan");
    expect(script).toContain("--staged");
    expect(script).toContain("--strict");
    expect(script).toContain("--json");
  });

  it("documents the --no-verify bypass", () => {
    expect(buildSecretsHookScript()).toContain("--no-verify");
  });

  it("exits non-zero on findings so git aborts the commit", () => {
    expect(buildSecretsHookScript()).toContain("exit 1");
  });
});

describe("isSecretsHookScript", () => {
  it("detects a script generated by buildSecretsHookScript", () => {
    expect(isSecretsHookScript(buildSecretsHookScript())).toBe(true);
  });

  it("does not match an unrelated hook script", () => {
    expect(isSecretsHookScript("#!/usr/bin/env bash\necho hello\n")).toBe(false);
  });

  it("does not match an empty string", () => {
    expect(isSecretsHookScript("")).toBe(false);
  });
});
